### SwiftLint – Standard Professional Configuration
### Compatible with Swift 6 / Xcode 16+

# Rules explicitly enabled (keeps config predictable)
opt_in_rules:
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closure_end_indentation
  - closure_parameter_position
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_first_not_nil
  - control_statement
  - discouraged_direct_init
  - duplicate_imports
  - empty_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - implicit_getter
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - line_length
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - nesting
  - opening_brace
  - private_action
  - private_outlet
  - private_over_fileprivate
  - redundant_objc_attribute
  - redundant_set_access_control
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - statement_position
  - switch_case_alignment
  - todo
  - trailing_comma
  - trailing_newline
  - type_name
  - unneeded_parentheses_in_closure_argument
  - unused_optional_binding
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition
  
analyzer_rules:
  - unused_import


# Rules disabled to allow flexible formatting and spacing
disabled_rules:
  - leading_whitespace
  - trailing_whitespace
  - vertical_whitespace
  - let_var_whitespace
  - closure_spacing
  - operator_usage_whitespace
  - no_space_in_method_call
  - indentation_width
  - file_header

# Custom rules (optional but recommended)
custom_rules:
  force_https:
    name: "Force HTTPS over HTTP"
    regex: "((?i)http(?!s))"
    match_kinds: string
    message: "Use HTTPS instead of HTTP"
    severity: error

# Paths excluded from linting
excluded:
  - Pods
  - Carthage
  - DerivedData
  - .build
  - fastlane
  - Generated

# Linting configuration
reporter: "xcode"

# Complexity and size limits
cyclomatic_complexity:
  - 20 # warning
  - 30 # error

type_body_length:
  - 400 # warning
  - 600 # error

function_body_length:
  - 80 # warning
  - 150 # error

file_length:
  - 600 # warning
  - 1000 # error

line_length:
  ignores_comments: true
  ignores_urls: true
  warning: 130
  error: 160
